### ISSUE TITLE
No module named 'PyQt5.QtWebKitWidgets'

### ISSUE THREAD

**Issue by blfpd** [UnitedRPMs/openshot#1]
I got this error after installing and launching Openshot:

``` bash
$ openshot-qt 
Loaded modules from installed directory: /usr/lib/python3.5/site-packages/openshot_qt
      launch:INFO ------------------------------------------------
      launch:INFO    OpenShot (version 2.0.7)
      launch:INFO ------------------------------------------------
         app:INFO openshot-qt version: 2.0.7
         app:INFO libopenshot version: 0.1.1
         app:INFO platform: Linux-4.5.5-300.fc24.x86_64-x86_64-with-fedora-24-Twenty_Four
         app:INFO processor: x86_64
         app:INFO machine: x86_64
         app:INFO python version: 3.5.1
         app:INFO qt5 version: 5.6.0
         app:INFO pyqt5 version: 5.6
    language:INFO Qt Detected Languages: ['fr-FR']
    language:INFO LANG Environment Variable: fr_FR.UTF-8
    language:INFO LOCALE Environment Variable: fr_FR
    language:INFO Attempting to load qt_fr_FR.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_fr in '/usr/share/qt5/translations'
    language:INFO Attempting to load fr_FR.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
    language:INFO Attempting to load fr/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
    language:INFO Attempting to load qt_fr_FR in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_fr in '/usr/share/qt5/translations'
    language:INFO Attempting to load fr_FR/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
    language:INFO Attempting to load fr/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
project_data:INFO Setting default profile to HDV 720 24p
    language:INFO Attempting to load qt_fr_FR.UTF-8 in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_fr in '/usr/share/qt5/translations'
    language:INFO Attempting to load fr_FR.UTF-8/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
    language:INFO Attempting to load fr/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
    language:INFO Attempting to load qt_fr_FR in '/usr/share/qt5/translations'
    language:INFO Attempting to load qt_fr in '/usr/share/qt5/translations'
    language:INFO Attempting to load fr_FR/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
    language:INFO Attempting to load fr/LC_MESSAGES/OpenShot in '/usr/lib/python3.5/site-packages/openshot_qt/locale'
         app:INFO Setting font to /usr/lib/python3.5/site-packages/openshot_qt/images/fonts/Ubuntu-R.ttf
         app:INFO Setting custom dark theme
      logger:ERROR Traceback (most recent call last):
      logger:ERROR   File "/usr/bin/openshot-qt", line 9, in <module>
      logger:ERROR load_entry_point('openshot-qt==2.0.7', 'gui_scripts', 'openshot-qt')()
      logger:ERROR   File "/usr/lib/python3.5/site-packages/openshot_qt/launch.py", line 69, in main
      logger:ERROR app = OpenShotApp(sys.argv)
      logger:ERROR   File "/usr/lib/python3.5/site-packages/openshot_qt/classes/app.py", line 144, in __init__
      logger:ERROR from windows.main_window import MainWindow
      logger:ERROR   File "/usr/lib/python3.5/site-packages/openshot_qt/windows/main_window.py", line 41, in <module>
      logger:ERROR from windows.views.timeline_webview import TimelineWebView
      logger:ERROR   File "/usr/lib/python3.5/site-packages/openshot_qt/windows/views/timeline_webview.py", line 38, in <module>
      logger:ERROR from PyQt5.QtWebKitWidgets import QWebView
      logger:ERROR ImportError
      logger:ERROR :
      logger:ERROR No module named 'PyQt5.QtWebKitWidgets'
     metrics:INFO Track metric: {'expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'last-modified': 'Sun, 17 May 1998 03:00:00 GMT', 'server': 'Golfe2', 'pragma': 'no-cache', 'content-location': 'http://www.google-analytics.com/collect?av=2.0.7&cd5=Fedora-24-Twenty+Four&aid=org.openshot.openshot-qt&aip=1&cid=57501d8e-6c19-46af-92c2-70415ddf7152&cd1=0.1.1&cd2=3.5.1&cd=initial-launch-screen&cd3=5.6.0&ua=Mozilla%2F5.0+%28X11%3B+Linux+x86_64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F37.0.2062.120+Safari%2F537.36&tid=UA-4381101-5&t=screenview&ul=en&cd4=5.6&v=1&an=OpenShot+Video+Editor', 'x-content-type-options': 'nosniff', 'content-length': '35', 'content-type': 'image/gif', 'access-control-allow-origin': '*', 'status': '200', 'date': 'Tue, 31 May 2016 00:05:30 GMT', 'cache-control': 'no-cache, no-store, must-revalidate', 'age': '777066'} (b'GIF89a\x01\x00\x01\x00\x80\xff\x00\xff\xff\xff\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02D\x01\x00;')
```

**Comment by sergiomb2** [comment]
rpm -qf /usr/lib64/python3.4/site-packages/PyQt5/QtWebKitWidgets.so 
python3-qt5-5.5.1-2.fc23.3.x86_64

so 

```
dnf install python3-qt5
```

but openshot requires python3-qt5 , anyway to test run:

```
python3 -c "from PyQt5.QtWebKitWidgets import QWebView; print (1)"
```

**Comment by blfpd** [comment]
Thanks, but I had `python3-qt5` installed already.
I solved it installing `python3-qt5-webkit`. Now launching :)
Shouldn't it be in the dependencies?

**Comment by sergiomb2** [comment]
@paulcarroty on  closed you should justify why , I see your commit ,  also you should bump the release .  have we already build and publish the package ?

Thanks

**Comment by paulcarroty** [comment]
@sergiomb2 yes.

**Comment by albertosouza** [comment]
Same problem with Fedora 24
fixed installing python3-qt5-webkit

**Comment by paulcarroty** [comment]
@albertosouza it's strange 'cause https://github.com/UnitedRPMs/openshot/blob/master/openshot.spec#L44

Which version of openshot you use?

```
# dnf info openshot
```

**Comment by albertosouza** [comment]
dnf info openshot comamnd log:

```
Última verificação de data de vencimento de metadados: 0:19:15 atrás em Wed Jul 20 14:09:14 2016.
Pacotes instalados
Nome        : openshot
Arq.        : noarch
Epoch       : 0
Versão      : 2.0.7
Lançamento  : 2.fc24
Tam.        : 110 M
Repo        : @System
A partir do : rpmfusion-free
Sumário     : Create and edit videos and movies
URL         : http://www.openshotvideo.com/
Licença     : GPLv3+
Descrição   : OpenShot Video Editor is a free, open-source, non-linear video editor. It
            : can create and edit videos and movies using many popular video, audio,
            : image formats.  Create videos for YouTube, Flickr, Vimeo, Metacafe, iPod,
            : Xbox, and many more common formats!
            : 
            : Features include:
            : * Multiple tracks (layers)
            : * Compositing, image overlays, and watermarks
            : * Support for image sequences (rotoscoping)
            : * Key-frame animation
            : * Video and audio effects (chroma-key)
            : * Transitions (lumas and masks)
            : * 3D animation (titles and simulations)
            : * Upload videos (YouTube and Vimeo supported)


```

**Comment by paulcarroty** [comment]
@albertosouza you don't use the URPMS repo:

```
A partir do : rpmfusion-free
```

Here's my log (F25, but the same depends) - check the '**' mark:

```
# dnf install openshot
Last metadata expiration check: 1:08:25 ago on Wed Jul 20 20:28:23 2016.
Dependencies resolved.
================================================================================================================
 Package                            Arch            Version                           Repository           Size
================================================================================================================
Installing:
 Field3D                            x86_64          1.7.2-2.fc25                      rawhide             518 k
 ImageMagick                        x86_64          6.9.3.0-3.fc25                    rawhide             169 k
 ImageMagick-c++                    x86_64          6.9.3.0-3.fc25                    rawhide             172 k
 ImageMagick-libs                   x86_64          6.9.3.0-3.fc25                    rawhide             2.2 M
 OpenColorIO                        x86_64          1.0.9-11.fc24                     rawhide             439 k
 OpenEXR-libs                       x86_64          2.2.0-5.fc24                      rawhide             630 k
 OpenImageIO                        x86_64          1.6.15-1.fc25                     rawhide             1.7 M
 SDL_image                          x86_64          1.2.12-14.fc24                    rawhide              46 k
 atlas                              x86_64          3.10.2-12.fc24                    rawhide             5.9 M
 blender                            x86_64          1:2.76-7.fc24                     rawhide              28 M
 boost-atomic                       x86_64          1.60.0-8.fc25                     rawhide              47 k
 boost-chrono                       x86_64          1.60.0-8.fc25                     rawhide              53 k
 boost-locale                       x86_64          1.60.0-8.fc25                     rawhide             278 k
 boost-program-options              x86_64          1.60.0-8.fc25                     rawhide             165 k
 boost-regex                        x86_64          1.60.0-8.fc25                     rawhide             299 k
 cfitsio                            x86_64          3.370-6.fc24                      rawhide             534 k
 fonts-blender                      noarch          1:2.76-7.fc24                     rawhide             4.7 M
 freexl                             x86_64          1.0.2-3.fc24                      rawhide              37 k
 gdal-libs                          x86_64          2.1.0-6.fc25                      rawhide             5.7 M
 geos                               x86_64          3.5.0-3.fc25                      rawhide             551 k
 goocanvas                          x86_64          1.0.0-10.fc24                     rawhide             145 k
 google-droid-sans-fonts            noarch          20120715-10.fc24                  rawhide             2.5 M
 hdf5                               x86_64          1.8.17-1.fc25                     rawhide             1.7 M
 ilmbase                            x86_64          2.2.0-5.fc24                      rawhide             105 k
 jemalloc                           x86_64          4.1.1-1.fc25                      rawhide             179 k
 leptonica                          x86_64          1.73-2.fc24                       rawhide             965 k
 libdap                             x86_64          3.17.2-1.fc25                     rawhide             615 k
 libgeotiff                         x86_64          1.4.0-7.fc24                      rawhide             712 k
 libgfortran                        x86_64          6.1.1-3.fc25                      rawhide             297 k
 libglade2                          x86_64          2.6.4-14.fc24                     rawhide              67 k
 libgta                             x86_64          1.0.7-3.fc24                      rawhide              38 k
 libkml                             x86_64          1.3.0-2.fc25                      rawhide             331 k
 libopenshot                        x86_64          0.1.1-3.fc25                      unitedrpms          307 k
 libopenshot-audio                  x86_64          0.1.1-2.fc25                      unitedrpms          1.5 M
 libquadmath                        x86_64          6.1.1-3.fc25                      rawhide             175 k
 libsodium                          x86_64          1.0.10-1.fc25                     rawhide             165 k
 libspatialite                      x86_64          4.3.0a-2.fc24                     rawhide             2.5 M
 libspnav                           x86_64          0.2.3-3.fc24                      rawhide              17 k
 libucil                            x86_64          0.9.10-12.fc24                    rawhide              73 k
 libunicap                          x86_64          0.9.12-17.fc24                    rawhide             122 k
 libwmf-lite                        x86_64          0.2.8.4-48.fc24                   rawhide              73 k
 mariadb-common                     x86_64          3:10.1.14-5.fc25                  rawhide              65 k
 mariadb-config                     x86_64          3:10.1.14-5.fc25                  rawhide              28 k
 mariadb-libs                       x86_64          3:10.1.14-5.fc25                  rawhide             647 k
 mlt                                x86_64          6.2.0-4.fc25                      unitedrpms          2.3 M
 mlt-python                         x86_64          6.2.0-4.fc25                      unitedrpms          124 k
 netcdf                             x86_64          4.4.1-2.fc25                      rawhide             721 k
 notify-python                      x86_64          0.1.1-30.fc24                     rawhide              38 k
 ogdi                               x86_64          3.2.0-0.26.beta2.fc24             rawhide             251 k
 opencv-contrib                     x86_64          3.1.0-6.fc25                      rawhide             3.4 M
 opencv-core                        x86_64          3.1.0-6.fc25                      rawhide             3.4 M
 openpgm                            x86_64          5.2.122-6.fc24                    rawhide             175 k
 **openshot**                           noarch          **2.0.7-6.fc25**                      unitedrpms           79 M
 opusfile                           x86_64          0.7-2.fc24                        rawhide              51 k
 postgresql-libs                    x86_64          9.5.3-3.fc25                      rawhide             245 k
 proj                               x86_64          4.9.2-2.fc24                      rawhide             208 k
 protobuf                           x86_64          2.6.1-4.fc24                      rawhide             356 k
 pugixml                            x86_64          1.7-2.fc24                        rawhide              92 k
 pygoocanvas                        x86_64          0.14.1-13.fc24                    rawhide              64 k
 pygtk2                             x86_64          2.24.0-14.fc25                    rawhide             914 k
 pygtk2-libglade                    x86_64          2.24.0-14.fc25                    rawhide              29 k
 python-qt5-rpm-macros              noarch          5.6-7.fc25                        rawhide              12 k
 python3-httplib2                   noarch          0.9.2-2.fc24                      rawhide             107 k
 python3-libopenshot                x86_64          0.1.1-3.fc25                      unitedrpms          335 k
 python3-numpy                      x86_64          1:1.11.1-1.fc25                   rawhide             3.0 M
 python3-qt5                        x86_64          5.6-7.fc25                        rawhide             4.0 M
 **python3-qt5-webkit**                 x86_64          5.6-7.fc25                        rawhide             133 k
 python3-sip                        x86_64          4.18-2.fc25                       rawhide             125 k
 python3-zmq                        x86_64          15.3.0-1.fc25                     rawhide             346 k
 pyxdg                              noarch          0.25-8.fc24                       rawhide              92 k
 qt-settings                        noarch          24-7.fc25                         rawhide              25 k
 qt5-qtbase                         x86_64          5.7.0-3.fc25                      rawhide             3.0 M
 qt5-qtbase-common                  noarch          5.7.0-3.fc25                      rawhide              30 k
 qt5-qtbase-gui                     x86_64          5.7.0-3.fc25                      rawhide             5.2 M
 qt5-qtconnectivity                 x86_64          5.7.0-2.fc25                      rawhide             451 k
 qt5-qtdeclarative                  x86_64          5.7.0-2.fc25                      rawhide             3.0 M
 qt5-qtenginio                      x86_64          1:1.6.1-2.fc25                    rawhide             172 k
 qt5-qtlocation                     x86_64          5.7.0-2.fc25                      rawhide             721 k
 qt5-qtmultimedia                   x86_64          5.7.0-2.fc25                      rawhide             782 k
 qt5-qtsensors                      x86_64          5.7.0-2.fc25                      rawhide             209 k
 qt5-qtserialport                   x86_64          5.7.0-2.fc25                      rawhide              66 k
 qt5-qtsvg                          x86_64          5.7.0-2.fc25                      rawhide             155 k
 qt5-qttools-common                 noarch          5.7.0-2.fc25                      rawhide              25 k
 qt5-qttools-libs-clucene           x86_64          5.7.0-2.fc25                      rawhide              50 k
 qt5-qttools-libs-designer          x86_64          5.7.0-2.fc25                      rawhide             2.7 M
 qt5-qttools-libs-help              x86_64          5.7.0-2.fc25                      rawhide             218 k
 qt5-qtwebchannel                   x86_64          5.7.0-2.fc25                      rawhide              85 k
 qt5-qtwebkit                       x86_64          5.7.0-2.fc25                      rawhide              10 M
 qt5-qtwebsockets                   x86_64          5.7.0-1.fc25                      rawhide              82 k
 qt5-qtx11extras                    x86_64          5.7.0-2.fc25                      rawhide              29 k
 qt5-qtxmlpatterns                  x86_64          5.7.0-2.fc25                      rawhide             1.1 M
 sox                                x86_64          14.4.2.0-6.fc24                   rawhide             406 k
 tesseract                          x86_64          3.04.01-2.fc25                    rawhide              11 M
 tinyxml                            x86_64          2.6.2-11.fc24                     rawhide              54 k
 unixODBC                           x86_64          2.3.4-3.fc25                      rawhide             424 k
 uriparser                          x86_64          0.8.4-3.fc25                      rawhide              53 k
 yaml-cpp03                         x86_64          0.3.0-9.fc24                      rawhide             151 k
 zeromq                             x86_64          4.1.4-5.fc25                      rawhide             554 k

Transaction Summary
================================================================================================================
Install  98 Packages
```

Please re-enable the URPMS repository as described here: https://github.com/UnitedRPMs/unitedrpms.github.io/blob/master/README.md

**Comment by albertosouza** [comment]
@paulcarroty i added this repository and fixed one strange update lock: https://www.reddit.com/r/Fedora/comments/4q8bly/error_the_operation_would_result_in_removing_the/

```
RPM Fusion for Fedora 24 - Free - Updates                                                                                               100 kB/s |  75 kB     00:00    
Pacotes instalados
Nome        : openshot
Arq.        : noarch
Epoch       : 0
Versão      : 2.0.7
Lançamento  : 6.fc24
Tam.        : 110 M
Repo        : @System
A partir do : unitedrpms
Sumário     : Create and edit videos and movies
URL         : http://www.openshotvideo.com/
Licença     : GPLv3+
Descrição   : OpenShot Video Editor is a free, open-source, non-linear video editor. It
            : can create and edit videos and movies using many popular video, audio,
            : image formats.  Create videos for YouTube, Flickr, Vimeo, Metacafe, iPod,
            : Xbox, and many more common formats!
            : 
            : Features include:
            : * Multiple tracks (layers)
            : * Compositing, image overlays, and watermarks
            : * Support for image sequences (rotoscoping)
            : * Key-frame animation
            : * Video and audio effects (chroma-key)
            : * Transitions (lumas and masks)
            : * 3D animation (titles and simulations)
            : * Upload videos (YouTube and Vimeo supported)

```

**Comment by sergiomb2** [comment]
I'm fixing it in RPMFusion , thks for the report .

**Comment by paulcarroty** [comment]
@albertosouza we don't use any dnf config for electron.
