### ISSUE TITLE
Version 2.1.0 doesn't run

### ISSUE THREAD

**Issue by ndias** [UnitedRPMs/openshot#2]
This is the error ...

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/openshot_qt/launch.py", line 45, in <module>
    from classes import info
ImportError: No module named 'classes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/openshot-qt", line 9, in <module>
    load_entry_point('openshot-qt==2.1.0', 'gui_scripts', 'openshot-qt')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2720, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2380, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2386, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/openshot_qt/launch.py", line 48, in <module>
    from openshot_qt.classes import info
  File "/usr/lib/python3.5/site-packages/openshot_qt/classes/info.py", line 69, in <module>
    for lang in os.listdir(os.path.join(PATH, 'locale')):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.5/site-packages/openshot_qt/locale'
```

**Comment by kuboosoft** [comment]
@ndias  I solved the error, don't worry. The update will be available in the coming hours . :)

**Comment by kuboosoft** [comment]
@ndias , Impatient? [here](https://github.com/UnitedRPMs/openshot/releases)
